version: '3.7'
services:
  app:
    build: .
    volumes:
      - .:/code
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.aws/credentials:/root/.aws/credentials
    networks:
      - openstax
networks:
  openstax:
    name: openstax
