AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Buy Print'

Parameters:
  EnvName:
    Type: String
    Description: The name of the environment, e.g. 'staging', 'production'

Resources:

  LambdaEdgeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../app/src
      Role: !GetAtt LambdaEdgeFunctionRole.Arn
      Runtime: python3.7
      Handler: lambda_function.lambda_handler
      Timeout: 5
      AutoPublishAlias: live

  LambdaEdgeFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      Path: "/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "AllowLambdaServiceToAssumeRole"
            Effect: "Allow"
            Action:
              - "sts:AssumeRole"
            Principal:
              Service:
                - "lambda.amazonaws.com"
                - "edgelambda.amazonaws.com"

  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: !Sub '${EnvName}-buy_print'
        DefaultCacheBehavior:
          LambdaFunctionAssociations:
            - EventType: origin-request
              LambdaFunctionARN: !Ref LambdaEdgeFunction.Version
          AllowedMethods:
            - 'HEAD'
            - 'GET'
          CachedMethods:
            - 'HEAD'
            - 'GET'
          Compress: false
          DefaultTTL: 0
          MaxTTL: 0
          MinTTL: 0
          ForwardedValues:
            Cookies:
              Forward: 'none'
            Headers:
              - 'CloudFront-Viewer-Country'
            QueryString: false
          TargetOriginId: DummyOrigin
          ViewerProtocolPolicy: 'redirect-to-https'
        Origins:
          - Id: DummyOrigin
            DomainName: openstax.org
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
        DefaultRootObject: ''
        Enabled: true
        HttpVersion: 'http1.1'
        IPV6Enabled: true
        PriceClass: 'PriceClass_All'

Outputs:
  LambdaEdgeFunction:
    Description: Lambda@Edge handler for content
    Value: !Ref LambdaEdgeFunction.Version
  DistributionId:
    Description: 'Id for our cloudfront distribution'
    Value: !Ref Distribution
  DistributionDomainName:
    Description: 'Domain name for our cloudfront distribution'
    Value: !GetAtt Distribution.DomainName

